# conf/config.yaml
defaults:
  - _self_
  - cv_stage: stage1
  - feature_select: none

cfg: src/config/lgbm_baseline.yaml
input: data/train/train.pkl

model_dir: ${hydra:runtime.output_dir}/models

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

