model_name: lgbm
random_state: 42
seed: 42

target_col: price_actual

# 除外する列
features_exclude:
  - time
  - timestamp   # raw datetime column removed before modeling
  - price_actual               # 目的変数そのもの
  - regex:^price_actual_.*$    # ラグ・移動統計も全部除外（正規表現）

params:
  bagging_fraction: 0.6017148242351481
  bagging_freq: 1
  feature_fraction: 0.6300984198048815
  lambda_l1: 0.4679255074098528
  lambda_l2: 0.7292183644505954
  learning_rate: 0.08117879677987437
  metric: rmse
  min_data_in_leaf: 35
  num_leaves: 79
  objective: rmse

cv:
  n_splits: 5            # TimeSeriesSplit 分割数
  test_hours: 720        # 各 fold の検証期間 (30 日)
  early_stopping_rounds: 50