model_name: lgbm
random_state: 42
seed: 42

target_col: price_actual

# 除外する列
features_exclude:
  - time
  - timestamp   # raw datetime column removed before modeling

params:
  objective: rmse
  metric: rmse
  learning_rate: 0.05
  num_leaves: 256
  feature_fraction: 0.8
  bagging_fraction: 0.8
  bagging_freq: 1
  min_data_in_leaf: 50
  lambda_l1: 0.1
  lambda_l2: 0.1

cv:
  n_splits: 5            # TimeSeriesSplit 分割数
  test_hours: 720        # 各 fold の検証期間 (30 日)
  early_stopping_rounds: 100